### PR TITLE
Disable requestAnimationFrame

### PR DESCRIPTION
**Pull request by oblador**
This PR addresses #12 by disabling `requestAnimationFrame` by default via monkey patch.

Also fixes race condition when inserting styles that disables CSS animations and transitions. 

On top of it, adds stories for all these cases. 

Ping @felquis

### CODE REVIEW

**Comment by felquis** [comment]
Our CI always timesout https://circleci.com/gh/pagarme/pilot/437

```
 ❯ Chrome (docker)
   ✖ Start
   
     Fetch list of stories
     Test chrome.palm
     Stop
Timeout
Error: Timeout
    at Timeout._onTimeout (/home/circleci/repo/webapp/node_modules/wait-on/lib/wait-on.js:91:10)
    at ontimeout (timers.js:471:11)
    at tryOnTimeout (timers.js:306:5)
    at Timer.listOnTimeout (timers.js:266:5)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
Exited with code 1
```

**Comment by oblador** [comment]
For this PR specifically, on master or on 0.7.0?

**Comment by felquis** [comment]
I installed loki from github using `oblador/loki#disable-raf`.

Using: `yarn build-storybook && yarn loki` is throws this error:
```
⋊> ~/p/p/webapp on shooting-stars  yarn loki                                                                                   15:00:25
yarn loki v0.27.5
$ "/home/felquis/pagarme/pilot/webapp/node_modules/.bin/loki"
loki test v0.7.0
 ✔ Chrome (docker)
Error: Uncaught [TypeError: source.close is not a function]
    at reportException (/home/felquis/pagarme/pilot/webapp/node_modules/loki/node_modules/jsdom/lib/jsdom/living/helpers/runtime-script-errors.js:66:24)
    at Timeout.callback (/home/felquis/pagarme/pilot/webapp/node_modules/loki/node_modules/jsdom/lib/jsdom/browser/Window.js:544:7)
    at ontimeout (timers.js:488:11)
    at tryOnTimeout (timers.js:323:5)
    at Timer.listOnTimeout (timers.js:283:5) TypeError: source.close is not a function
    at handleDisconnect (evalmachine.<anonymous>:66561:12)
    at Window.<anonymous> (evalmachine.<anonymous>:66536:7)
    at Timeout.callback (/home/felquis/pagarme/pilot/webapp/node_modules/loki/node_modules/jsdom/lib/jsdom/browser/Window.js:542:19)
    at ontimeout (timers.js:488:11)
    at tryOnTimeout (timers.js:323:5)
    at Timer.listOnTimeout (timers.js:283:5)
Done in 25.19s.
```

----

Using `yarn build-storybook && loki --reactUri="file:./storybook-static"` sometimes it runs with success but others with `socket hang up` error.

```
     ❯ Grid
       ✖ Column sizes
         → read ECONNRESET
       ✖ Responsive
         → socket hang up
       ✖ Proportional sizes
         → read ECONNRESET
       ✖ Size combinations
         → read ECONNRESET
       ✖ Flexible
         → read ECONNRESET
     ❯ ContextSwitch
       ✖ All styles
         → socket hang up
     ❯ Filters
       ✖ Default
         → socket hang up
   ✔ Stop
Some visual tests failed to run
error Command failed with exit code 1.


⋊> ~/p/p/webapp on shooting-stars  yarn visual-tests                                                                           15:02:09
yarn visual-tests v0.27.5
$ yarn build-storybook && loki --reactUri="file:./storybook-static" 
@storybook/react v3.2.8

=> Loading custom addons config.
=> Loading custom webpack config (extending mode).
Building storybook ...
loki test v0.7.0
 ✔ Chrome (docker)
Done in 41.34s.
⋊> ~/p/p/webapp on shooting-stars                                                                                              15:03:21
```

I'm not sure how can I help, I'm using `Linux name.. 4.10.0-37-generic #41~16.04.1-Ubuntu SMP Fri Oct 6 22:42:59 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux`, node 8.1.2, you can run this code on this PR/branch https://github.com/pagarme/pilot/pull/274

**Comment by oblador** [comment]
@felquis Thanks, I'll try to reproduce. The start timeout might be due to downloading the docker image taking time. I'll try to configure circleci to the project too to catch any issues like this.

**Comment by felquis** [comment]
About the raf fix, it works great but I'd prefer to always let it in it's final frame, now it stays in the first frame.

chrome_palm_progress_circular

**Comment by oblador** [comment]
@felquis I've fixed the `source.close` crash and refactored to use the final instead of first frame. Tried this branch against your repo and worked well for all I could tell. 

Please confirm and I'll cut a release shortly. Beware though that you'll get text rendering differences because of the switch of chrome docker image. You might need to `yarn cache clean && rm -rf node_modules && yarn` as yarn has some caching issues when installing stuff from git.

**Pull request merged**
