### PR TITLE
Migrate docs website to Docusaurus

### PR DESCRIPTION
**Pull request by oblador**
Gitbook went closed source and are generally a pain to work with. 

### Merge blockers
- [x] Approval from @tjenkinson to use BBC logo

### Preview

Skärmavbild 2019-09-14 kl  19 16 39

### CODE REVIEW

**Comment by techeverri** [comment]
The new docs website looks awesome! 🔥

**Comment by techeverri** [comment]
How can I help to translate to Spanish?

I saw a comment at the top of `website/i18n/en.json`

```json
"_comment": "This file is auto-generated by write-translations.js",
```

Is there a command I can run to preview the translations?

**Comment by oblador** [comment]
@techeverri Don’t think Spanish is needed yet, thanks for the offer though!

**Comment by oblador** [comment]
@tjenkinson Great, I'll update it to use text instead of logo then. Think it would be awesome to feature Loki on your website 👍

**Pull request merged**
