### PR TITLE
Update siteConfig.js

### PR DESCRIPTION
**Pull request by ndonovic**
Add Toptal to the list of users.

### CODE REVIEW

**Comment by oblador** [comment]
Cool! Would you mind adding an SVG logo too?

**Comment by ndonovic** [comment]
@oblador Uploads are disabled and it doesn't seem like I can fork loki/website/static/img/users/ unless I'm missing something. Github doesn't allow me to upload an svg, but it does allow for png upload. What I have is the logo in 1395 × 383. Please let me know if that will work or if I can get that to you another way? 
toptal

**Comment by ndonovic** [comment]
@oblador Since Github doesn't allow for uploading of svgs here, it allows for zip, so I'm going to zip the SVG logo for you and upload it to this comment. 
[toptal.svg.zip](https://github.com/oblador/loki/files/4617765/toptal.svg.zip)

**Comment by ndonovic** [comment]
Not sure if the commits went through here or not, but regardless I have opened a new pull request. Feel free to ignore the other if it went through correctly @oblador , thank you.

**Comment by ndonovic** [comment]
@oblador Thanks, saw you approved! 

It might be just me but I don't see it on the page even though it looks like everything was entered correctly. Does it take some time or was there an error there?

**Comment by oblador** [comment]
Typically the website is only deployed with new releases to keep the documentation in sync with the latest available version and not confuse users with upcoming features, but I made a manual deploy now :-)

**Comment by ndonovic** [comment]
> Typically the website is only deployed with new releases to keep the documentation in sync with the latest available version and not confuse users with upcoming features, but I made a manual deploy now :-)

Thank you so much, have a great rest of your day and week!

**Pull request merged**
