### PR TITLE
Add Warren to Users of Loki

### PR DESCRIPTION
**Pull request by emkis**
Hello there! We are currently using Loki on our Storybook ([Nebraska](https://docs.dev.warren.com.br/nebraska)). We thought that it would be really cool to be on your list of users. Thanks a lot

### CODE REVIEW

**Review by oblador — APPROVED** [review]

**Comment by oblador** [comment]
Sweet!

**Comment by emkis** [comment]
Thank youuu, I just looked at the site in production, and it is not there yet, I think you forget to deploy it, or did not execute the action automatically

**Comment by oblador** [comment]
Hey! It seems the svg you attached is broken somehow, do you have another one that renders in Chrome?

**Comment by oblador** [comment]
Managed to find one on your website and it should be deployed now!

**Pull request merged**
