### PR TITLE
feat: swap chalk→turbocolor / minimist→getopts

### PR DESCRIPTION
**Pull request by jorgebucaran**
Hi @oblador! 

This PR swaps chalk and minimist for [turbocolor](https://github.com/jorgebucaran/turbocolor) and [getopts](https://github.com/jorgebucaran/getopts) respectively. All packages share virtually the same API, the main difference is turbocolor/getopts have 10x~20x faster load time and runtime and no deps :)

Let me know if this looks good to you and if you want to accept my contribution. 👋 

---

#### turbocolor/chalk

```
# Load Time
chalk: 15.190ms
turbocolor: 0.777ms

# All Colors
chalk × 8,729 ops/sec
turbocolor × 158,383 ops/sec

# Chained Colors
chalk × 1,838 ops/sec
turbocolor × 39,830 ops/sec

# Nested Colors
chalk × 4,049 ops/sec
turbocolor × 59,833 ops/sec
```

#### getopts/minimist

```
minimist × 283,031 ops/sec
getopts × 1,495,165 ops/sec
```

### CODE REVIEW

**Comment by oblador** [comment]
Hi and thank you for your PR! 

Since they are both only run at most once per execution (which can take minutes) these performance gains doesn't really move the needle. Would also argue it's more likely that people will have these packages installed via other dependencies already. 

What are your thoughts @nowells & @techeverri?

**Comment by techeverri** [comment]
Thanks for the PR @jorgebucaran =)

I agree with you @oblador, you can see that both `chalk` and `minimist` weren't removed from the `yarn.lock` file because we have them installed via our dependencies.

**Comment by jorgebucaran** [comment]
@oblador @techeverri No problem at all! Thank you, for having a look :)

Cheers!

**Comment by oblador** [comment]
Closing this one then, thanks for your contribution though @jorgebucaran 🙇

**Pull request closed without merging**
