### PR TITLE
Use yukinying/chrome-headless-browser-stable docker image to support Apple M1 chips

### PR DESCRIPTION
**Pull request by cheyer**
Loki is currently not working on Apple M1 computers since the chrome headless browser image used is not build for `arm64` architectures.

Just recently the maintainer of the chrome headless browser image has [solved the issue](https://github.com/yukinying/chrome-headless-browser-docker/issues/46) and also publishes images for `arm64` and `amd64`: https://hub.docker.com/r/yukinying/chrome-headless-browser-stable/tags/

This PR introduces the `chrome-headless-browser-stable` image to loki, since it [recommended now](https://github.com/yukinying/chrome-headless-browser-docker#chrome-headless-browser-stable).

This should solve following issues:
- https://github.com/oblador/loki/issues/344
- https://github.com/oblador/loki/issues/348

### CODE REVIEW

**Comment by techeverri** [comment]
Reposting here for visibility 👇 

https://github.com/oblador/loki/issues/348#issuecomment-1102769717

> Please note, you can pass any custom (or newer) Docker image when running `loki test`
> 
> https://loki.js.org/command-line-arguments.html#loki-test
> 
> > `--chromeDockerImage`
> > What docker image to use when running chrome

https://github.com/oblador/loki/issues/348#issuecomment-1102774595

> > Loki currently does not seem to work in Docker on M1 Macs. You can find more details in another issue: #344
> 
> Loki itself doesn't require any update to work on laptops with M1. In the other hand, the default Docker image used to run the tests against a container didn't support M1 laptops. But it does now [yukinying/chrome-headless-browser-docker#46 (comment)](https://github.com/yukinying/chrome-headless-browser-docker/issues/46#issuecomment-1099787883)

**Comment by techeverri** [comment]
Reposting here for visibility 👇 

https://github.com/oblador/loki/issues/348#issuecomment-1102769717

> Please note, you can pass any custom (or newer) Docker image when running `loki test`
> 
> https://loki.js.org/command-line-arguments.html#loki-test
> 
> > `--chromeDockerImage`
> > What docker image to use when running chrome

https://github.com/oblador/loki/issues/348#issuecomment-1102774595

> > Loki currently does not seem to work in Docker on M1 Macs. You can find more details in another issue: #344
> 
> Loki itself doesn't require any update to work on laptops with M1. In the other hand, the default Docker image used to run the tests against a container didn't support M1 laptops. But it does now [yukinying/chrome-headless-browser-docker#46 (comment)](https://github.com/yukinying/chrome-headless-browser-docker/issues/46#issuecomment-1099787883)

**Review by oblador — APPROVED** [review]
Absolutely fantastic! I've verified it on my M1 and works great 👍

**Comment by cheyer** [comment]
Hey @oblador 👋 
Would you consider creating and publishing a new version to NPM?

**Comment by oblador** [comment]
I've been on vacation and have some things I want to get in before a new version, but you shouldn't _need_ a new version, just update your config to use the new docker image.

**Comment by techeverri** [comment]
> I've been on vacation and have some things I want to get in before a new version, but you shouldn't need a new version, just update your config to use the new docker image.

Check https://github.com/oblador/loki/pull/382#issuecomment-1103754251 for more details @cheyer @jaronschulz

**Comment by oblador** [comment]
Released in [0.30.0](https://github.com/oblador/loki/releases/tag/v0.30.0)

**Comment by donaldpipowitch** [comment]
I just tried Loki 0.30 with the new docker image (also in the 101.x and latest version of the image) and it runs pretty good, but only 90% of the images are rendered like there are rendered on non-M1 devices. Any idea why?

I also tried Colima (as mentioned [here](https://twitter.com/bfletcherbiggs/status/1509271921434759170/photo/1)), but it is way too slower. (It's even faster to let Loki run in our CI and download the generated artefacts.)

**Comment by cheyer** [comment]
> I just tried Loki 0.30 with the new docker image (also in the 101.x and latest version of the image) and it runs pretty good, but only 90% of the images are rendered like there are rendered on non-M1 devices. Any idea why?
> 
> I also tried Colima (as mentioned [here](https://twitter.com/bfletcherbiggs/status/1509271921434759170/photo/1)), but it is way too slower. (It's even faster to let Loki run in our CI and download the generated artefacts.)

@donaldpipowitch When testing images created with a M1 device on old MBP and Windows machines of colleagues we also ran into a couple of stories failing. We could fix the issue for us by increasing the tolerance to 1%, so
```
yarn loki test --chromeTolerance 1
```

**Comment by NikoHelle** [comment]
Hi, we're also getting different results from CI pipeline and tests run locally on a M1 device. We've tried with multiple different Chrome Docker images. About 95% of the images pass and failed images have only very small pixel shifts - usually with texts.

We could increase `--chromeTolerance`, but it would be better to find out what is causing these differences. Chrome is run in Docker so images should match.

Specs:
- we are using Loki 0.30.3.
- our CI is Github actions with Ubuntu 20.4.
- we've tested with default Chrome image and yukinying/chrome-headless-browser-stable:latest and other Chrome images found in Docker hub which support arm64.
- tests run locally with Intel Mac match CI images

Any ideas what is causing the differences? Could it be a font issue as most differences are related to texts shifting?

**Comment by ahsan-rao** [comment]
Hey @NikoHelle, were you able to find a solution to the different images issue? We are also facing the same problem. Images pushed up from Intel Macs do not cause the CI pipeline to fail. But if we try it with M1 Mac, its showing differences and the CI pipelines tests fail.

**Comment by NikoHelle** [comment]
@ahsan-rao 

We updated loki to 0.30.3 and used these settings in .lokirc.json

```
"pixelmatch": {
    "threshold": 0.2,
    "alpha": 1,
    "diffColor": [255, 0, 255]
  }
```

We tested with different `threshold` values and ended up with 0.2 being the smallest stable value in CI. Some reference images were also re-created. `Alpha` and `diffColor` do not affect the tests, just wanted clearer diff images. :) 

There have been no false negatives in our tests since the update.

**Comment by ahsan-rao** [comment]
Thanks @NikoHelle. So this new Loki config isn't breaking the CI and the Loki tests are running smoothly between M1 and Intel machines. There is another issue right now. So lets say all images are generated on an intel chip. I pull it down on my M1 and run `loki:test`, there is no failure. But if I run `loki:update` on my M1 many reference images(intel generated) get updated even though there were no differences detected earlier. Same thing applies vice versa. One thing we can do is run the update command for only those images that show differences. Have you faced something similar before? Thanks in advance!

**Comment by NikoHelle** [comment]
Sorry, I can't verify how `loki update` should work. I'm not sure, if it re-creates all images anyway or compare old and new ones and discard the ones that have not changed.

**Pull request merged**
