### PR TITLE
Fix JSDOM environment

### PR DESCRIPTION
**Pull request by oblador**
Addresses #3, #5, #41

### CODE REVIEW

**Comment by creaux** [comment]
`clearimmediate` too.

**Comment by oblador** [comment]
@creaux Gotcha, test the commit I just pushed.

**Comment by creaux** [comment]
Seems that update maybe introduced some other issue.
```
Cannot read property 'indexOf' of null
Error: Cannot read property 'indexOf' of null
    at createError (/Users/xxx/loki/src/targets/chrome/fetch-storybook.js:10:14)
    at Worker.worker.on.message (/Users/xxx/loki/src/targets/chrome/fetch-storybook.js:33:16)
    at emitTwo (events.js:131:20)
    at Worker.emit (events.js:214:7)
    at ChildProcess.Worker.process.on (internal/cluster/worker.js:42:12)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at emit (internal/child_process.js:772:12)
    at _combinedTickCallback (internal/process/next_tick.js:141:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)

```

**Comment by oblador** [comment]
@creaux Would you care to share your project so I can debug it?

**Comment by creaux** [comment]
@oblador sorry that won't be possible :(

**Comment by oblador** [comment]
Ok, can you give me some minimal example to reproduce the issue then? Is your storybook throwing any errors when running it in the browser?

**Pull request merged**
