### PR TITLE
Make docker seccomp usage opt-out

### PR DESCRIPTION
**Pull request by oblador**
For me and potentially others (#92, #94) Chrome in Docker wouldn't work on CI without seccomp settings. 

This PR reverts #14 and adds a `--chromeDockerWithoutSeccomp` flag to explicitly opt out of it. **It is  breaking change!**

@ldabiralai Do you think we could get rid of the `dockerAsSudo` flag now?

### CODE REVIEW

**Comment by ldabiralai** [comment]
@oblador I'll test if this works for us instead of `dockerAsSudo` :)

**Comment by oblador** [comment]
Amazing, do you think you could test without a release?

**Comment by ldabiralai** [comment]
Yeah, that should be fine!

**Comment by ldabiralai** [comment]
@oblador unfortunately running with `chromeDockerWithoutSeccomp` and not `dockerWithSudo` doesn't work for us. We have the same error as before.

**Comment by oblador** [comment]
Thanks for reporting, then we'll keep it!

**Pull request merged**
