### PR TITLE
Be more graceful when the selector is not valid: take a screenshot of 'body' in that case.

### PR DESCRIPTION
**Pull request by priomsrb**
Sometimes my stories look fine in the browser, but Loki complains that the selector isn't valid.

This can happen in many cases. For example: if my component is absolutely positioned, then the selector would have a 0 width and height. In those cases it might be better to just capture a screenshot of the entire body rather than throw an error.

One of the things I like about Loki is that it requires minimal configuration and tweaking to get it working. So I think it should avoid throwing errors if the story looks fine in the user's browser.

### CODE REVIEW

**Comment by oblador** [comment]
Thanks! This looks good to me, @techeverri WDYT?

**Comment by techeverri** [comment]
Taking the screenshot of the whole body, Isn't this going to include the Storybook elements? :thinking:

Seems this could give people the false sense that everything is fine even when they're expecting the screenshot to be a portion of the screen (e.g. using a decorator). IMO returning false positives is not a good thing, it makes hard to distinguish between an error and the fallback.

**Comment by priomsrb** [comment]
Hey @techeverri . Sorry for the delayed reply.

> Taking the screenshot of the whole body, Isn't this going to include the Storybook elements? 🤔

Loki takes screenshots of the `/iframe.html` page which doesn't include storybook elements. So taking a screenshot of the body will not include storybook elements.

> Seems this could give people the false sense that everything is fine even when they're expecting the screenshot to be a portion of the screen (e.g. using a decorator).

Could you clarify what you meant by "using a decorator"? I didn't fully understand this part.

> IMO returning false positives is not a good thing, it makes hard to distinguish between an error and the fallback.

I'm not sure I would call it a false positive. Rather, in the current situation, viewing certain stories in the browser works fine, but when loki tries to take a screenshot it fails. I'll link some examples where I've encountered this to clarify what I mean.

**Comment by priomsrb** [comment]
Here's a link to 2 examples that currently cause an error: https://github.com/oblador/loki/issues/115#issuecomment-442280516

The changes in this PR will fix the errors by taking a screenshot of the body.

**Comment by oblador** [comment]
With recent developments in this project, stuff like fixed/absolute positioning is now better supported, so I'm going to close this PR.

**Pull request closed without merging**
